AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Serverless video watermaker'er'

Parameters:
  LambdaLayerArn:
    Type: String
    Default: 'arn:aws:lambda:us-east-1:XXXXXXXXXXXX:layer:ffmpeg:1'
  ConversionFileType:
    Type: String
    Default: mp4
  ConversionMimeType:
    Type: String
    Default: video/mp4v-es
  S3ResourceBucket:
    Type: String
    Default: 'devopstar'
  S3ResourceKeyIcon:
    Type: String
    Default: 'resources/aws-ffmpeg-serverless-convert/base/icon.png'

Resources:

  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", ['uploads', Ref: 'AWS::StackName']]

  ResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", ['results', Ref: 'AWS::StackName']]

  ConvertFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Timeout: 900
      MemorySize: 1024
      Runtime: nodejs8.10
      CodeUri: ../src
      Layers:
        - !Ref LambdaLayerArn
      Policies:
        - S3ReadPolicy:
            BucketName: !Join ["-", ['uploads', Ref: 'AWS::StackName']]
        - S3CrudPolicy:
            BucketName: !Join ["-", ['results', Ref: 'AWS::StackName']]
        - S3ReadPolicy:
            BucketName: !Ref S3ResourceBucket
      Environment:
        Variables:
          OUTPUT_BUCKET: !Join ["-", ['results', Ref: 'AWS::StackName']]
          EXTENSION: !Sub '.${ConversionFileType}'
          MIME_TYPE: !Ref ConversionMimeType
          RESOURCE_BUCKET: !Ref S3ResourceBucket
          ICON_FILE: !Ref S3ResourceKeyIcon
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref UploadBucket
            Events: s3:ObjectCreated:*

Outputs:

  UploadBucket:
    Description: "Upload S3 bucket"
    Value: !Ref UploadBucket

  ResultsBucket:
    Description: "Results S3 bucket"
    Value: !Ref ResultsBucket

