AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Serverless video thumbnail builder

Parameters:
  LambdaLayerArn:
    Type: String
    Default: 'arn:aws:lambda:us-east-1:277790246569:layer:ffmpeg:1'
  ConversionFileType:
    Type: String
    Default: png
  ConversionMimeType:
    Type: String
    Default: image/png
  ThumbnailWidth:
    Type: Number
    Default: 500

Resources:

  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", ['uploads', Ref: 'AWS::StackName']]

  ResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", ['results', Ref: 'AWS::StackName']]

  ConvertFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Timeout: 180
      MemorySize: 1024
      Runtime: nodejs8.10
      CodeUri: ../src
      Layers:
        - !Ref LambdaLayerArn
      Policies:
        - S3CrudPolicy:
            BucketName: !Join ["-", ['uploads', Ref: 'AWS::StackName']]
        - S3CrudPolicy:
            BucketName: !Join ["-", ['results', Ref: 'AWS::StackName']]
      Environment:
        Variables:
          OUTPUT_BUCKET: !Join ["-", ['results', Ref: 'AWS::StackName']]
          EXTENSION: !Sub '.${ConversionFileType}'
          MIME_TYPE: !Ref ConversionMimeType
          THUMB_WIDTH: !Ref ThumbnailWidth
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref UploadBucket
            Events: s3:ObjectCreated:*

Outputs:

  UploadBucket:
    Description: "Upload S3 bucket"
    Value: !Ref UploadBucket

  ResultsBucket:
    Description: "Results S3 bucket"
    Value: !Ref ResultsBucket

